[project]
name = "serper_scrape_tool"
version = "0.1.0"
description = "Power up your crews with serper_scrape_tool"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.201.1"
]

[tool.crewai]
type = "tool"
